version: '3.1'
services:

    db:
        image: mysql:5.7.35
        container_name: db
        restart: always
        volumes:
            - ./Database:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
        networks:
            - dev
        ports:
            - "3306:3306"

    phpmyadmin:
        image: phpmyadmin
        container_name: phpMyadmin
        restart: always
        depends_on:
            - db
        ports:
            - "8080:80"
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: root
        networks:
            - dev

    maildev:
        image: maildev/maildev
        container_name: mail
        command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
        ports:
          - "8081:80"
        restart: always
        networks:
            - dev
            
    site1:
        build: ./site1
        container_name: site1
        ports:
          - "5000:80"
        volumes:
            - ./site1/vhosts:/etc/apache2/sites-enabled
            - ./site1/www:/var/www
        restart: always
        networks:
            - dev

    site2:
        build: ./site2
        container_name: site2
        ports:
          - "5001:80"
        volumes:
            - ./site2/vhosts:/etc/apache2/sites-enabled
            - ./site2/www:/var/www
        restart: always
        networks:
            - dev

networks:
    dev: